### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fslp#1]
* [ ] Constants
  * [ ] Named colors
  * [ ] Arrow head types
  * [ ] Node shapes
  * [ ] License types
  * [ ] GraphViz rendering control constants
* [ ] Fundamental types
  * [ ] Positive real numbers
  * [ ] Non-negative integers
  * [ ] Labels
    * [ ] Atoms
    * [ ] Strings
  * [ ] URLs
* [ ] Calculators
  * [ ] Color
    * [ ] RGB3
    * [ ] RGB6
    * [ ] RGBA4
    * [ ] RGBA8
* [ ] Combiners
  * [ ] Semver
  * [ ] Stripe
  * [ ] Cycle
  * [ ] License (license type or custom string)
* [ ] State declarations
* [ ] Inline states
* [ ] Arrows
* [ ] Arrow decorators
* [ ] Expressions
* [ ] Subexpressions
* [ ] Machine configuration
* [ ] Machine attributes
